languageCode = "en-au"
languageName = "English (Australia)"
displayName = ":flag-au:"
isoCode = "en-AU"
weight = 1
rtl = false

title = " "
#logo = "img/logo.jpg"
description = "Bla "
copyright = "&copy; 2022 Stefano Pupe"

dateFormat = "2 January 2006"

[author]
  name = "Stefano Pupe"
  image = "img/avatar_smaller.png"
  headline = "Data Scientist"
  bio = " "
  links = [
    { linkedin = "https://linkedin.com/in/spupe" },
    { github = "https://github.com/spupe" },
	{ researchgate = "https://www.researchgate.net/profile/Stefano-Pupe" },

  ]
